# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506a181805566a14dc2137689aa3874aa41d167a4cd6b9caf53b100ee9769ac33e3b9b4a5b284b98be3d30887badc5f63801e6b0e69998524afcb4bfcb1fc37e

test:
  secret_key_base: 7f8852e1e24f38faa580f3b0e74fe8e291aabbbb6e09ef29330e8401d26f830093490c3a57dae3a663aa91e3be8d6d22d47048d3456205f36d85685a18ff7960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
