# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce08acd0c49dd38b42ac5c228d2fb258d96fab5f0dd0e9d91a1c9a0efeea9b46aa156476bb62576504464ba1c4f795ee0216e10e31338471a8b2ed5923fd23f

test:
  secret_key_base: 771a534988743adf2158922bff4f89c854794823775808a063599464dab3890e14dd0e15aa6eef5d12c587d475839bc70d1bb46dc2c4aca6cb2baaec649f1c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
