# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f869297cfc400ccc246c37d9fb11c77328a0a30ab63b33b4d341363ec0b7e1b210d255ef6179255a7bc6a89c5fd0a349efeed1e528aba873615dcb941e3c56d

test:
  secret_key_base: d5f096da942f40e59fa46002ad385d0269027b72b335d619e60bcf6b78661090713de31662288c1ffb9da42e31bf6b8cd05877763353dca574d3f33b66953096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
