# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a52bd6e8c751ffcd6710828abdf448c0e4beb80ae7474323fe8570daf2ba40f1314b4677c3211e84cad8cbef7b0039b28f3adb3813300b281e173be8b85697b0

test:
  secret_key_base: f999f429f8c63f9bbe86eba20cfa2ae7c7b9e902927c271f4fda57893f3265821197013853ccb55c3dbd4487ad991425fe36108d6840169da2ff9490735fee31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
