# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 497d43705c2e46e992dcc6479b7f5903e4854aa9b311deec41e8dc33fd82c8da0874a97ac9edf6662067b6404c6a551f16a630da906674183d7720d08ac467ba

test:
  secret_key_base: e140dd427c06d15ee0b65558e2ddf13d3a177540b2e565ab2313cfbf1e7eef775aea0c65dc1d1020c038230079090124ef5f493ec48cdcf915d53be016aa044e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
