# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54d3086e5b9c2dc969c8d12a1bd12e9d902e41c2b811a8c48f0d9b43f4e600537b143ccbd8a9397e00493cd2e37bc68f2a78f26f591e4a3fcf9224d94ff9f58

test:
  secret_key_base: 180842f75272827bb5977a45ff7f380fe23c0b2a96749d987bc4e353234069b70b879e7728411aa809a215869bed7aa6bc7056677c17739fb02e69cafb6ca7a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
